# Configuration for pre-commit (see https://pre-commit.com/)
# A framework for managing and maintaining multi-language pre-commit hooks.

# Requires the pre-commit package manager to be installed: pip install pre-commit

# To install pre-commit into your git hooks (i.e. at .git/hooks/pre-commit), run 'pre-commit install'.
# To update hooks to the latest version automatically, run 'pre-commit autoupdate'. By default, this will bring the
# hooks to the latest tag on the default branch.

# NOTE: in this implementation, tox runs 'pre-commit run -a'

# A list of repository mappings.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # see https://github.com/pre-commit/pre-commit-hooks
      - id: check-ast
        description: Simply check whether files parse as valid python
      - id: check-builtin-literals
        description: Require literal syntax when initializing empty or zero Python builtin types
#      - id: check-json
#        description: Attempts to load all json files to verify syntax
      - id: check-yaml
        description: Attempts to load all yaml files to verify syntax
      - id: detect-aws-credentials
        description: Checks for the existence of AWS secrets that you have set up with the AWS CLI
      - id: detect-private-key
        description: Checks for the existence of private keys
      - id: double-quote-string-fixer
        description: This hook replaces double quoted strings with single quoted strings.
      - id: end-of-file-fixer
        description: Makes sure files end in a newline and only a newline
      - id: fix-byte-order-marker
        description: removes UTF-8 byte order marker
      - id: fix-encoding-pragma
        args: ['--remove']
        description: Remove # -*- coding: utf-8 -*- to the top of python files
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character
      - id: name-tests-test
        description: Assert that files in tests/ end in _test.py
      - id: requirements-txt-fixer
        description: Sorts entries in requirements.txt and removes incorrect entry for pkg-resources==0.0.0
#      - id: trailing-whitespace  # removes trailing whitespace from test files too!
#        description: Trims trailing whitespace


#  - repo: https://github.com/python/black
#    rev: 20.8b1
#    hooks:
#      - id: black
#        language_version: python3

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
#        additional_dependencies: [flake8-import-order]  # conflicts with PyCharm's Optimize imports

  - repo: local
    hooks:
      - id: sphinx-build
        name: sphinx documentation build
        entry: python -m sphinx.cmd.build
        args: [-a, -E, docs, docs/_build]  # removed -W due to autosummary warnings, TODO find a way to use it
        language: system
        files: ^docs
        types: [file]
        pass_filenames: false
#      # https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html#module-sphinx.ext.doctest
#      - id: sphinx-doctest
#        name: sphinx doctest
#        entry: python -m sphinx-build
#        args: [-a, -E, -b, doctest, docs, docs/_build]
#        language: system
#        files: ^docs
#        types: [file]
#        pass_filenames: false

#  - repo: https://github.com/pre-commit/pygrep-hooks
#    rev: v1.7.0
#    hooks:
#      # Detect common mistake of using single backticks when writing rst
#      - id: rst-backticks
#
#  - repo: https://github.com/myint/rstcheck
#    rev: 3f92957478422df87bd730abde66f089cc1ee19b
#    hooks:
#      # Checks syntax of reStructuredText and code blocks nested within it.
#      - id: rstcheck
#        additional_dependencies: [rstcheck]
