dist: focal
language: python
cache: pip
python:
  - "nightly"
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
before_install:
  - sudo apt-get -y update
  - pip install --upgrade pip wheel
install:
  - sudo apt-get -y install build-essential libpoppler-cpp-dev pkg-config python-dev tesseract-ocr
  - pip install --upgrade aioxmpp beautifulsoup4 chump cssbeautifier jsbeautifier keyring matrix_client msgpack
    pdftotext Pillow pushbullet.py pyppeteer pytesseract redis vobject coverage docutils flake8 flake8-import-order
    pytest
script:
# runs coverage and pytest (see .coveragerc)
  - coverage run
after_success:
# uploads coverage data to https://codecov.io/gh/mborsetti/webchanges
  - bash <(curl -s https://codecov.io/bash)
