language: python
cache: pip
python:
  - "3.9"
  - "3.8"
  - "3.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install flake8 flake8-builtins flake8-import-order pytest coverage
  - sudo apt-get install -y build-essential libpoppler-cpp-dev pkg-config python-dev tesseract-ocr
  - pip install pdftotext docutils pygments pytesseract pillow
script:
  - coverage run --source=webchanges -m pytest -v
  - coverage report -m
#  - coverage html
