# codecov.yaml configuration file for Codecov (see https://docs.codecov.io/docs/codecovyml-reference)

coverage:
  status:
    patch: false
    changes: false
    project:
      default:
        target: auto

ignore:
  - tests
  - docs

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true   # if true: only post the comment if coverage changes
  require_base: yes       # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches:               # branch names that can post comment
    - unreleased
    - main
