coverage:
  status:
    patch: false
    changes: false
    project:
      default:
        target: auto

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: true   # if true: only post the comment if coverage changes
  require_base: yes       # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
