[tool.black]
# See https://black.readthedocs.io/en/stable/pyproject_toml.html
line-length = 120
target-version = ['py39', 'py38', 'py37', 'py36']
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
